### ISSUE TITLE
Code for wooyay/verificationportal

### ISSUE THREAD

**Issue by muchemwal** [martinschefflerTSI/cwa-allinone#1]
Hi martin are you able to share the code you used to build your docker image for the verificationportal. I notice there are some differences from the main code at https://github.com/corona-warn-app/cwa-verification-portal.git

**Comment by martinschefflerTSI** [comment]
Hi, 
I directly built the docker images from the provided sources and pushed them to the docker repo. What differences do you mean?

**Comment by muchemwal** [comment]
Hi Martin,
Thank you for getting back to me, when I build my own portal image And use it with your verification server, I only change the templates to English, I get an Internal error Generating the TeletTAN, so I assumed there could have been minor code changes when you built your images. If I use your image everything works fine. I even tried building my own image from the source without any changes i still get the internal error "Es kann keine TeleTAN aufgrund eines internen Fehlers generiert werden."
Steps to reproduce.
git clone https://github.com/corona-warn-app/cwa-verification-portal.git
$ cd cwa-verification-portal
$ mvn package
$ docker build -f "Dockerfile" -t cwa-verification-portal .
$ docker tag cwa-verification-portal:latest muchemwal/cwa-verification-portal:latest
$ docker push muchemwal/cwa-verification-portal:latest

on the docker-compose.yml i pointed to that image as below:
  verificationportal:
    container_name: verificationportal
    image: muchemwal/cwa-verification-portal:latest

then i run 
$ docker-compose up

when the containers areup i then add a user on iam before trying to generate the TeleTAN.

There could be something i am doing wrong somewhere.

**Comment by martinschefflerTSI** [comment]
Well I only manually push docker images of full versions of CWA - these are not daily builds or something. Actually I am not directly involved with the project ATM, the docker images are not "official" in any way.
I will check out the latest version of CWA and push newer images, let's see if I can reproduce your error with the latest stable version

**Comment by muchemwal** [comment]
Thanks for taking your time, i look forward to your response.

**Comment by martinschefflerTSI** [comment]
I updated docker images to version 1.0.2 and I actually got your internal server error!
It seems that the URL for teletan generation changed from http://localhost:8081/cwa/teletan to http://localhost:8081/cwa/start
I updated the readme accordingly.
Cheers,
Martin

**Comment by muchemwal** [comment]
Thank you
